### PR TITLE
reworking API for 1.0.0 release

### PR DESCRIPTION
**Pull request by drewfish**
- bin/dep-audit reports all packages which fail the policy check
- bin/dep-audit inteprets --hook relative to current working directory
- programmatic API reports all passing and failing package@versions
- programmatic API takes hook in options
- programmatic API is now following the "nodeback" convention

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by drewfish** [comment]
@jl3329 and @bengl do you have any feedback on this? The general idea is to change the API a little bit to (a) make it more consistent with community conventions, and (b) have it report _all_ policy violations so that the user has the full list of things which need attention.

**Comment by vsacheti** [comment]
👍

**Comment by bengl** [comment]
LGTM

**Pull request merged**
